services:
  salon-app:
    image: ghcr.io/elksandro2/sass-salon/salon-app:latest
    container_name: salon-app
    env_file:
      - .env
    ports:
      - "80:8080" # Redireciona a porta 80 externa para a 8080 do contêiner unificado
    restart: always
    networks:
      - salon-network

volumes: {}

networks:
  salon-network:
    external: true
