services:
  salon-app:
    image: ghcr.io/des-sist-corp-ufpb/eq03:latest
    container_name: salon-app
    env_file:
      - .env
    ports:
      - "8103:8080"
    restart: always
    networks:
      - salon-network

volumes: {}

networks:
  salon-network:
    external: true
