services:
  db:
    image: postgres:16
    container_name: salon-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: salon_dev
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d salon_dev" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - salon-network

  mailpit:
    image: axllent/mailpit
    container_name: salon-mailpit
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # UI Web do Mailpit
    networks:
      - salon-network

  salon-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salon-app
    env_file:
      - .env
    environment:
      - DB_URL=jdbc:postgresql://db:5432/salon_dev
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started
    networks:
      - salon-network

volumes:
  pgdata:

networks:
  salon-network:
    driver: bridge
