spring:
  application:
    name: salon
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  jackson:
    time-zone: America/Recife

mail:
  api-url: ${MAIL_API_URL:https://api.resend.com}
  password: ${MAIL_PASSWORD:}
  from: ${MAIL_FROM:dev@localhost.com}
  business: ${MAIL_BUSINESS:salao@localhost.com}

logging:
  level:
    root: INFO
    com.cristiane.salon: DEBUG
    org.springframework.security: DEBUG

mercadopago:
  access-token: ${MERCADO_PAGO_ACCESS_TOKEN}
  webhook-secret: ${MERCADO_PAGO_WEBHOOK_SECRET}
