spring:
  application:
    name: salon
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

mail:
  api-url: ${MAIL_API_URL:https://api.resend.com}
  password: ${MAIL_PASSWORD:}
  from: ${MAIL_FROM:dev@localhost.com}
  business: ${MAIL_BUSINESS:salao@localhost.com}

logging:
  level:
    root: INFO
    com.cristiane.salon: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/salon.log
    max-size: 10MB
    max-history: 10

mercadopago:
  access-token: ${MERCADO_PAGO_ACCESS_TOKEN}
  webhook-secret: ${MERCADO_PAGO_WEBHOOK_SECRET}
